### ISSUE TITLE
Sync-ComputerState.ps1

### ISSUE THREAD

**Issue by scriptingstudio** [ViPiC-Ru/admin.tools#2]
Зачем `$source`, если он не используется, тем более проверять?
При посылке WOL `$target` не нужно проверять, т.к. это броадкаст, все равно ответа нет. Еще зависит, разрешен ли WOL  в биосе (в Windows по умолчанию включен). Например, в Dell и HP отключено.

**Comment by ViPiC-Ru** [comment]
Приветствую. `Sync-ComputerState.ps1` **очень частный** скрипт. Он просто решают одну из моих маленьких домашних задач. У меня два ПК дома (ПК и мини ПК). Скрипт включает мини ПК когда включен основной ПК и выключает мини ПК когда выключен основной ПК. Что бы не бегать и не включать/выключать мини ПК.

Скрипт больше про это, нежили про WOL. В данном случае `$source` и `$target` это не отправитель и получатель WOL пакета, а исходный и целевой компьютер. Да, ты прав WOL всегда по броадкасту идёт, я как раз для этого использую `[System.Net.IPAddress]::Broadcast` что бы не писать `255.255.255.255`. Спасибо за обратную связь.
